wlan-caf: wcnss_service: Add missing include for unistd.h
hardware/qcom-caf/wlan/wcnss-service/wcnss_service.c:153:11: error: implicit declaration of function 'write' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

Change-Id: I316fa21738820b41226c0736a39276aa98148e57